cough_classification/urls.py
from django.contrib import admin
from django.urls import path, include


from django.urls import re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

# from . import views

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    
    path('', include('main.urls')),
    path("admin/", admin.site.urls),
    path('users/', include('users.urls')),
    # path('detection/', include('users.urls')),
    # path('', views.homepage),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

from django.conf.urls.static import static
from django.conf import settings

app_name = 'main'
urlpatterns = [
    path('', views.home, name='home'),
    path('project/', views.project, name='project'),
    path('research/', views.research, name='research'),
    path('static/<path:file_path>/', views.serve_file, name='open_file'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views


app_name = 'users'

urlpatterns = [
    # Using custom form creation
    # path('register/', views.register_view, name="register"),
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    # path('upload-audio/', views.upload_audio, name='upload_audio'),
    # path("record-audio/", views.record_audio, name="record_audio"),
    # path("upload-audio/", views.upload_audio, name="upload_audio"),
    
    
    path("dashboard/", views.DashboardInputView.as_view(), name="dashboard_input"),
    path("dashboard/results/", views.DashboardResultsView.as_view(),name="dashboard_results"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    
    

    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" crossorigin="anonymous"> -->
 
    <!-- default icons used in the plugin are from Bootstrap 5.x icon library (which can be enabled by loading CSS below) -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.min.css" crossorigin="anonymous">
    
    <!-- alternatively you can use the font awesome icon library if using with `fas` theme (or Bootstrap 4.x) by uncommenting below. -->
    <!-- link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" crossorigin="anonymous" -->
    
    <!-- the fileinput plugin styling CSS file -->
    <link href="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/css/fileinput.min.css" media="all" rel="stylesheet" type="text/css" />
    
    <!-- if using RTL (Right-To-Left) orientation, load the RTL CSS file after fileinput.css by uncommenting below -->
    <!-- link href="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/css/fileinput-rtl.min.css" media="all" rel="stylesheet" type="text/css" /-->
    
    <!-- the jQuery Library -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" crossorigin="anonymous"></script>
    
    <!-- buffer.min.js and filetype.min.js are necessary in the order listed for advanced mime type parsing and more correct
        preview. This is a feature available since v5.5.0 and is needed if you want to ensure file mime type is parsed 
        correctly even if the local file's extension is named incorrectly. This will ensure more correct preview of the
        selected file (note: this will involve a small processing overhead in scanning of file contents locally). If you 
        do not load these scripts then the mime type parsing will largely be derived using the extension in the filename
        and some basic file content parsing signatures. -->
    <script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/js/plugins/buffer.min.js" type="text/javascript"></script>
    <script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/js/plugins/filetype.min.js" type="text/javascript"></script>
    
    <!-- piexif.min.js is needed for auto orienting image files OR when restoring exif data in resized images and when you
        wish to resize images before upload. This must be loaded before fileinput.min.js -->
    <script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/js/plugins/piexif.min.js" type="text/javascript"></script>
    
    <!-- sortable.min.js is only needed if you wish to sort / rearrange files in initial preview. 
        This must be loaded before fileinput.min.js -->
    <script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/js/plugins/sortable.min.js" type="text/javascript"></script>
    
    <!-- bootstrap.bundle.min.js below is needed if you wish to zoom and preview file content in a detail modal
        dialog. bootstrap 5.x or 4.x is supported. You can also use the bootstrap js 3.3.x versions. -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    
    <!-- the main fileinput plugin script JS file -->
    <script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/js/fileinput.min.js"></script>
    
    <!-- following theme script is needed to use the Font Awesome 5.x theme (`fa5`). Uncomment if needed. -->
    <!-- script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/themes/fa5/theme.min.js"></script -->
    
    <!-- optionally if you need translation for your language then include the locale file as mentioned below (replace LANG.js with your language locale) -->
    <script src="https://cdn.jsdelivr.net/gh/kartik-v/bootstrap-fileinput@5.5.0/js/locales/LANG.js"></script>
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">

    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">



    {% block head_block %}
    {% endblock head_block %}
    
    <title>
        {% block title %}
            VOCOVID
        {% endblock title %}
    </title>
</head>
<body>
    <div class="col-md-8">
        {% if messages %} {% for message in messages %}
        <div class="alert alert-{{ message.tag }}">{{ message }}</div>
        {% endfor%} {% endif %} {% block content %}{% endblock %}
    </div>
    <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
            <div class="container-fluid">
                <a class="nav-link" href="{% url 'main:home' %}">
                    <span class="navbar-brand mb-0 h1">VOCOVID</span>
                </a>
            </div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link {% if request.resolver_match.url_name == 'home' %}active{% endif %}" aria-current="page" href="{% url 'main:home' %}">Home</a>
                    <a class="nav-link {% if request.resolver_match.url_name == 'project' %}active{% endif %}" aria-current="page" href="{% url 'main:project' %}">Project</a>
                   <a class="nav-link {% if request.resolver_match.url_name == 'research' %}active{% endif %}" aria-current="page" href="{% url 'main:research' %}">Research</a>
                    
                    {% if user.is_authenticated %}
                        <a class="nav-link {% if request.resolver_match.url_name == 'detection' %}active{% endif %}" aria-current="page" href="{% url 'users:dashboard_input' %}">Dashboard</a>
                        {% comment %} <form action="{% url 'users:logout' %}" method="post">
                            {% csrf_token %}
                            <button>Logout</button>
                        </form> {% endcomment %}
                        <a href="{% url 'users:logout' %}" class="nav-link" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            Logout
                        </a>

                        <form id="logout-form" action="{% url 'users:logout' %}" method="post" style="display: none;">
                            {% csrf_token %}
                        </form>
                    {% else %}    
                        <div class="dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Login</a>

                            <ul class="dropdown-menu dropdown-menu-end">
                                <li><a class="dropdown-item" href="{% url 'users:login' %}">Login</a></li>
                                <li><a class="dropdown-item" href="{% url 'users:register' %}">Create an account</a></li>
                            </ul>
                        </div>
                    {% endif %}
                    
                </div>
            </div>
        </div>
    </nav>
    
    {% block body %}
    {% endblock body %}
    {% comment %} <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script> {% endcomment %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>